### ISSUE TITLE
missing packages encountered when running pytest

### ISSUE THREAD

**Issue by ricopicone** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#10]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/docs/code_testing.md?plain=1#L12

With a fresh installation, I get
```
ModuleNotFoundError: No module named 'eigenpy'
```
and 
```
ModuleNotFoundError: No module named 'pydrake'
```
I didn't install Drake, so the latter may be expected. It looks like EigenPy can't be installed with `pip` either.

After installing EigenPy, I'm also getting
```
ModuleNotFoundError: No module named 'crocoddyl'
```
I tried to `pip` which their site says should work, but no packages were found.

**Comment by fwiebe** [comment]
Hi @ricopicone, I tested the pip version of crocoddyl and it should be compatible with the code in this repository. Did you upgrade pip with

pip install --upgrade pip

before trying to install crocoddyl?

The pip version of drake is also compatible now. Both crocoddyl and drake are added now in the setup.py (see f0d24ba1f7fbcd02fdb77ecc78a4a6c110cf4919)

**Comment by fwiebe** [comment]
Hi @ricopicone, for Crocoddyl we now recommend the installation through robotpgk (see the [Crocoddyl github page]( https://github.com/loco-3d/crocoddyl)). The whole installation and code testing workflow is now continuously tested for ubuntu 18.04/python 3.6 and ubuntu 20.04/python 3.8 with the github actions api (see f356b8d374d0438c54eb506dc5b5699b70419aa4).
Let me know if you are still having problems with dependency installations.
