### ISSUE TITLE
cannot be run as root

### ISSUE THREAD

**Issue by ricopicone** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#11]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/docs/installation_guide.md?plain=1#L243

The script returns an error that it can't be run as root. Remove `sudo` from this line.

**Comment by fwiebe** [comment]
Switched to the pip version of drake (f0d24ba1f7fbcd02fdb77ecc78a4a6c110cf4919). The manual installation is no longer necessary and the guide was removed.
