### ISSUE TITLE
wrong "B" matrix in lqr_controller.py 

### ISSUE THREAD

**Issue by Jarvis861** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#13]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/software/python/simple_pendulum/controllers/lqr/lqr_controller.py#L39

Hi, "B" matrix is probably wrong. It should be  _self.B = np.array([[0, 1/self.m/self.len**2.0]]).T_. But this small issue does not affect the final result too much as shown below.

- True
![3 1 lqr_true](https://user-images.githubusercontent.com/72842611/144807615-b270b6ed-dcd6-44ac-8474-f96058ebfeea.png)

- False
![3 2 lqr_false](https://user-images.githubusercontent.com/72842611/144807681-2777c66f-3dd8-48a9-86cf-efb061e9549c.png)

Finally, thanks for your sharing! This project does greatly enhance my understanding of control methods.

**Comment by fwiebe** [comment]
Thanks for your feedback. You are right. I fixed the B matrix.
