### ISSUE TITLE
"J" and "m*cx" are inaccurate in system_identification.py

### ISSUE THREAD

**Issue by Jarvis861** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#14]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/software/python/simple_pendulum/model/system_identification.py#L87-L88

Hi, **J** and **m*cx** may not be accurate in dynamics. It would be better to change to **I** (Interia) and **m** respectively.

**Comment by shivesh1210** [comment]
@Jarvis861 Thanks for pointing out the wrong description in the comment. I have corrected it. J is the inertia and m*cx is the mass times center of mass (com) of the system. If you observe the equations, it is not possible to identify the mass and com of the system independently and hence we use m*cx.

**Comment by Jarvis861** [comment]
You are right! I forgot the length.
