### ISSUE TITLE
length to CoM 0.045 is wrong

### ISSUE THREAD

**Issue by Jarvis861** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#15]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/hardware/testbench_description.md?plain=1#L20

Hi, the length to CoM here is 0.45m instead of 0.045m.

**Comment by shivesh1210** [comment]
Thanks for pointing the typo. Fixed in https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/commit/ea1bd3f107a7fe86d82ab097d2021795aca11ee8
