### ISSUE TITLE
paper comments

### ISSUE THREAD

**Issue by jingnanshi** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#16]
Thank you for open sourcing this library. Here are my comments regarding the submitted version of the paper:

p2: It will be aesthetically more pleasing for the fonts of the variables to be consistent with the equation below. Also mention that the symbols are defined in the equation will be helpful.

p3: Number the equation and reference it in Figure 1.

p2: CubeMars_AK_V1.1: is this the actual model number of the controller board? If so, provide the reference to the manual if possible.

p7: Figure 5: While the criteria have been defined on the previous page, the definitions of how percentages are calculated are not entirely clear. Maybe provide some explanations.

Let me know if you have more questions. Thank you.

**Comment by fwiebe** [comment]
Hello @jingnanshi , thank you very much for your feedback. I addressed your comments in the last commit (95033728de5b57a93b9a829b239c62d3595e8d51)
