### ISSUE TITLE
Title cases in paper.bib

### ISSUE THREAD

**Issue by jingnanshi** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#18]
For your entries in paper.bib, please for this guideline: https://pandoc.org/MANUAL.html#citations.

In particular, the titles should be capitalized in title case.

**Comment by fwiebe** [comment]
Hello @jingnanshi, The titles in the paper.bib file are now capitalized (see 95033728de5b57a93b9a829b239c62d3595e8d51). Thanks again for the feedback.
