### ISSUE TITLE
setup github actions workflow for continuous integration

### ISSUE THREAD

**Issue by shivesh1210** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#19]
We should setup a CI/CD pipeline via github so that we can ensure that the software package is always installable on a clean system and the unit testing works.

You need to include a yml file in order to do this. An example to set this up on github was pointed to me via Alexander Fabisch here: https://github.com/rock-learning/pytransform3d/blob/master/.github/workflows/python-package.yml

Some further help on this can be found here:
1. Building and testing with python: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
2. Supported runners and hardware resources: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
3. Getting started with actions: https://docs.github.com/en/actions
4. Installing dependency software on Ubuntu runners: https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners

**Comment by fwiebe** [comment]
Thanks for the suggestion and the links to get started!

This was implemented in f356b8d374d0438c54eb506dc5b5699b70419aa4. 
Automated software installation and code testing for this repository as well as automated documentation generation is set up.
