### ISSUE TITLE
define positive theta

### ISSUE THREAD

**Issue by ricopicone** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#3]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/paper/paper.md?plain=1#L113

It appears Figure 1 to be counter-clockwise, but it should be mentioned explicitly here.

**Comment by fwiebe** [comment]
I added an explicit remark (see commit 393f0b08e1e9882cec9a3be3d568ee7c78263e88)
