### ISSUE TITLE
clarify simulation-based and otherwise

### ISSUE THREAD

**Issue by ricopicone** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#4]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/paper/paper.md?plain=1#L147

Figure 3 is quite helpful in showing which aspects of the control algorithms rely on the simulation. Please clarify this also in the text of this section (e.g. when introducing trajectory optimization, state that this happens in simulation)

**Comment by fwiebe** [comment]
Clarified this also in the text (see commit 393f0b08e1e9882cec9a3be3d568ee7c78263e88)
