### ISSUE TITLE
frequency = speed

### ISSUE THREAD

**Issue by ricopicone** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#5]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/paper/paper.md?plain=1#L199

I believe you have called speed "frequency" in the figure. Please change either the figure or the text. (Nice figure, btw.)

**Comment by fwiebe** [comment]
You are right. There was a mix up. Fixed it to "frequency" in the text (393f0b08e1e9882cec9a3be3d568ee7c78263e88)
