### ISSUE TITLE
trajectory following clarification

### ISSUE THREAD

**Issue by ricopicone** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#6]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/paper/paper.md?plain=1#L161

Clarify how the "closed-loop" and "RL" controllers differ from trajectory following. Consider if there might be a better term besides "closed-loop," considering these are all actually closed-loop in the usual sense.

**Comment by fwiebe** [comment]
Thanks for your feedback @ricopicone! You are right, the categories were a bit ambiguous. I changed the categories to "trajectory-based control" and "policy-based control" (6caf96f4663ef8034b60dbd6d34ced5f1d8d5081) to highlight that some controllers try to follow a specific (precomputed) trajectory and others operate on a state-space covering policy. Hope this is more clear and in no conflict with common terminology.
