### ISSUE TITLE
benchmarks simulated?

### ISSUE THREAD

**Issue by ricopicone** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#7]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/paper/paper.md?plain=1#L186

It seems likely that these benchmarks are simulated, but I didn't see this mentioned

**Comment by fwiebe** [comment]
Yes, the benchmarks are simulated. It is explicitly mentioned it in the text now. (see commit 393f0b08e1e9882cec9a3be3d568ee7c78263e88)
