### ISSUE TITLE
does the simulation have three uses?

### ISSUE THREAD

**Issue by ricopicone** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#8]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/paper/paper.md?plain=1#L122

It seems the simulation can be used to:

1. precompute trajectories and RL models;
2. simulate the function of the "Main Control Loop" without hardware-in-the-loop (HIL); and
3. simulate during HIL "real time control," presumably for certain specific control schemes that require this.

- [ ] I'm not positive if 3 is the meaning intended in the referenced line, so if not, please re-word.
- [ ] Figure 3 shows "Pendulum" at the bottom, but since you can do item (2), please split this into a "Pendulum" (HIL) block and a "Simulation" block

**Comment by fwiebe** [comment]
Yes, the simulation can be used for all three of these cases. I added a sentence to make this more clear in the dynamics section and changed Figure 3 as proposed. (see commit 393f0b08e1e9882cec9a3be3d568ee7c78263e88).
