### ISSUE TITLE
encoder

### ISSUE THREAD

**Issue by ricopicone** [dfki-ric-underactuated-lab/torque_limited_simple_pendulum#9]
https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/blob/222c610b6ce8e684f7141c1eeddbeb8f85f45b65/hardware/testbench_description.md?plain=1#L25

Include at least a mention that there's an encoder in this for feedback

**Comment by shivesh1210** [comment]
addressed in https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum/commit/514fe6d0260e6c0c46eb1c5e8c6f5e2d7863a32a
